version: '3'

services:

  wordpress2:
    image: wordpress:latest
    deploy:
      resources:
        limits:
          memory: 258M
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db2
      WORDPRESS_DB_NAME: wordpress2
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./wordpress2:/var/www/html
    depends_on:
      - db2


  db2:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress2
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db2_data:/var/lib/mysql


volumes:
  db2_data: